<?php

namespace Database\Seeders;

use App\Models\Course;
use Illuminate\Database\Seeder;

class CoursesSeeder extends Seeder
{
    public function run(): void
    {
        $courses = [
            [
                'title'          => 'Forex Trading Fundamentals',
                'title_ar'       => 'أساسيات تداول الفوركس',
                'title_en'       => 'Forex Trading Fundamentals',
                'category'       => 'forex',
                'description'    => 'Learn the basics of forex markets.',
                'description_ar' => 'تعلم أساسيات سوق العملات الأجنبية، أزواج العملات، والتحليل الفني والأساسي لبدء رحلتك في التداول.',
                'description_en' => 'Learn the basics of forex markets, currency pairs, and technical & fundamental analysis to start your trading journey.',
                'level_ar'       => 'مبتدئ',
                'level_en'       => 'Beginner',
                'duration_ar'    => '6 أسابيع',
                'duration_en'    => '6 Weeks',
                'price'          => 299.00,
                'duration_hours' => 12,
                'sessions'       => 12,
                'enrolled'       => 1234,
                'status'         => 'active',
            ],
            [
                'title'          => 'Advanced Technical Analysis',
                'title_ar'       => 'التحليل الفني المتقدم',
                'title_en'       => 'Advanced Technical Analysis',
                'category'       => 'forex',
                'description'    => 'Master candlestick patterns and advanced indicators.',
                'description_ar' => 'إتقان الشموع اليابانية، مؤشرات RSI و MACD، واستراتيجيات الدعم والمقاومة المتقدمة.',
                'description_en' => 'Master candlestick patterns, RSI & MACD indicators, and advanced support/resistance strategies.',
                'level_ar'       => 'متقدم',
                'level_en'       => 'Advanced',
                'duration_ar'    => '8 أسابيع',
                'duration_en'    => '8 Weeks',
                'price'          => 499.00,
                'duration_hours' => 16,
                'sessions'       => 16,
                'enrolled'       => 876,
                'status'         => 'active',
            ],
            [
                'title'          => 'Cryptocurrency Trading',
                'title_ar'       => 'تداول العملات الرقمية',
                'title_en'       => 'Cryptocurrency Trading',
                'category'       => 'crypto',
                'description'    => 'Complete guide to trading Bitcoin, Ethereum & altcoins.',
                'description_ar' => 'دليلك الشامل لتداول البيتكوين والإيثريوم والعملات البديلة مع استراتيجيات إدارة المخاطر.',
                'description_en' => 'Complete guide to trading Bitcoin, Ethereum & altcoins with risk management strategies.',
                'level_ar'       => 'مبتدئ',
                'level_en'       => 'Beginner',
                'duration_ar'    => '5 أسابيع',
                'duration_en'    => '5 Weeks',
                'price'          => 399.00,
                'duration_hours' => 10,
                'sessions'       => 10,
                'enrolled'       => 2145,
                'status'         => 'active',
            ],
            [
                'title'          => 'DeFi & Decentralized Finance',
                'title_ar'       => 'DeFi والتمويل اللامركزي',
                'title_en'       => 'DeFi & Decentralized Finance',
                'category'       => 'crypto',
                'description'    => 'Explore DeFi world, yield farming, and lending protocols.',
                'description_ar' => 'اكتشف عالم التمويل اللامركزي، yield farming، وبروتوكولات الإقراض والاقتراض.',
                'description_en' => 'Explore DeFi world, yield farming, and lending/borrowing protocols.',
                'level_ar'       => 'متوسط',
                'level_en'       => 'Intermediate',
                'duration_ar'    => '4 أسابيع',
                'duration_en'    => '4 Weeks',
                'price'          => 349.00,
                'duration_hours' => 8,
                'sessions'       => 8,
                'enrolled'       => 678,
                'status'         => 'active',
            ],
            [
                'title'          => 'US Stock Market Investing',
                'title_ar'       => 'الاستثمار في الأسهم الأمريكية',
                'title_en'       => 'US Stock Market Investing',
                'category'       => 'stocks',
                'description'    => 'Learn to analyze US blue-chip stocks and build a diversified portfolio.',
                'description_ar' => 'تعلم تحليل أسهم الشركات الأمريكية الكبرى مثل Apple و Tesla واستراتيجيات بناء محفظة متنوعة.',
                'description_en' => 'Learn to analyze US blue-chip stocks like Apple & Tesla and build a diversified portfolio.',
                'level_ar'       => 'متوسط',
                'level_en'       => 'Intermediate',
                'duration_ar'    => '7 أسابيع',
                'duration_en'    => '7 Weeks',
                'price'          => 449.00,
                'duration_hours' => 14,
                'sessions'       => 14,
                'enrolled'       => 1567,
                'status'         => 'active',
            ],
            [
                'title'          => 'Trading Risk Management',
                'title_ar'       => 'إدارة المخاطر في التداول',
                'title_en'       => 'Trading Risk Management',
                'category'       => 'forex',
                'description'    => 'Capital protection strategies, stop-loss, and position sizing.',
                'description_ar' => 'استراتيجيات حماية رأس المال، وقف الخسارة، وتحديد حجم الصفقة المناسب.',
                'description_en' => 'Capital protection strategies, stop-loss, and proper position sizing.',
                'level_ar'       => 'متوسط',
                'level_en'       => 'Intermediate',
                'duration_ar'    => '4 أسابيع',
                'duration_en'    => '4 Weeks',
                'price'          => 249.00,
                'duration_hours' => 8,
                'sessions'       => 8,
                'enrolled'       => 923,
                'status'         => 'active',
            ],
            [
                'title'          => 'Futures Trading',
                'title_ar'       => 'تداول العقود الآجلة',
                'title_en'       => 'Futures Trading',
                'category'       => 'stocks',
                'description'    => 'Learn futures trading for commodities and indices.',
                'description_ar' => 'تعلم تداول العقود الآجلة للسلع والمؤشرات مع استراتيجيات التحوط المتقدمة.',
                'description_en' => 'Learn futures trading for commodities and indices with advanced hedging strategies.',
                'level_ar'       => 'متقدم',
                'level_en'       => 'Advanced',
                'duration_ar'    => '6 أسابيع',
                'duration_en'    => '6 Weeks',
                'price'          => 549.00,
                'duration_hours' => 12,
                'sessions'       => 12,
                'enrolled'       => 432,
                'status'         => 'active',
            ],
            [
                'title'          => 'Trading Psychology',
                'title_ar'       => 'سيكولوجية التداول',
                'title_en'       => 'Trading Psychology',
                'category'       => 'forex',
                'description'    => 'Learn to control emotions and build a successful trader mindset.',
                'description_ar' => 'تعلم التحكم في مشاعرك أثناء التداول وبناء عقلية المتداول الناجح.',
                'description_en' => 'Learn to control emotions while trading and build a successful trader mindset.',
                'level_ar'       => 'مبتدئ',
                'level_en'       => 'Beginner',
                'duration_ar'    => '3 أسابيع',
                'duration_en'    => '3 Weeks',
                'price'          => 199.00,
                'duration_hours' => 6,
                'sessions'       => 6,
                'enrolled'       => 1876,
                'status'         => 'active',
            ],
            [
                'title'          => 'NFTs & Digital Assets',
                'title_ar'       => 'NFT والرموز غير القابلة للاستبدال',
                'title_en'       => 'NFTs & Digital Assets',
                'category'       => 'crypto',
                'description'    => 'Understand the NFT market and how to evaluate digital assets.',
                'description_ar' => 'فهم سوق NFT وكيفية تقييم وتداول الأصول الرقمية.',
                'description_en' => 'Understand the NFT market and how to evaluate and trade digital assets.',
                'level_ar'       => 'مبتدئ',
                'level_en'       => 'Beginner',
                'duration_ar'    => '3 أسابيع',
                'duration_en'    => '3 Weeks',
                'price'          => 279.00,
                'duration_hours' => 6,
                'sessions'       => 6,
                'enrolled'       => 534,
                'status'         => 'active',
            ],
            [
                'title'          => 'Options Trading',
                'title_ar'       => 'تداول الخيارات Options',
                'title_en'       => 'Options Trading',
                'category'       => 'stocks',
                'description'    => 'Options strategies from Calls & Puts to complex strategies.',
                'description_ar' => 'استراتيجيات تداول الخيارات من Call و Put إلى Spread والاستراتيجيات المعقدة.',
                'description_en' => 'Options strategies from Calls & Puts to Spreads and complex strategies.',
                'level_ar'       => 'متقدم',
                'level_en'       => 'Advanced',
                'duration_ar'    => '8 أسابيع',
                'duration_en'    => '8 Weeks',
                'price'          => 599.00,
                'duration_hours' => 16,
                'sessions'       => 16,
                'enrolled'       => 345,
                'status'         => 'active',
            ],
        ];

        foreach ($courses as $data) {
            Course::firstOrCreate(
                ['title' => $data['title']],
                $data
            );
        }
    }
}
