<?php

namespace Database\Seeders;

use App\Models\KpiDefinition;
use Illuminate\Database\Seeder;

class KpiDefinitionsSeeder extends Seeder
{
    public function run(): void
    {
        $kpis = [

            // ── Marketer ──────────────────────────────────────────────────
            [
                'role'           => 'marketer',
                'slug'           => 'activity_rate',
                'name_ar'        => 'معدل النشاط',
                'name_en'        => 'Activity Rate',
                'description_ar' => 'متوسط (إعجابات + تعليقات + مشاركات) ÷ متابعين × 100',
                'description_en' => 'Average (likes + comments + shares) ÷ followers × 100',
                'unit'           => '%',
                'direction'      => 'higher_is_better',
                'max_bonus_pct'  => 40,
                'tier_a_min'     => 2,   'tier_a_bonus' => 10,
                'tier_b_min'     => 6,   'tier_b_bonus' => 25,
                'tier_c_min'     => 10,  'tier_c_bonus' => 40,
                'sort_order'     => 1,
            ],
            [
                'role'           => 'marketer',
                'slug'           => 'follower_growth',
                'name_ar'        => 'نمو المتابعين',
                'name_en'        => 'Follower Growth',
                'description_ar' => 'نسبة النمو الشهري عبر جميع المنصات',
                'description_en' => 'Monthly growth rate across all platforms',
                'unit'           => '%',
                'direction'      => 'higher_is_better',
                'max_bonus_pct'  => 45,
                'tier_a_min'     => 2,   'tier_a_bonus' => 15,
                'tier_b_min'     => 6,   'tier_b_bonus' => 30,
                'tier_c_min'     => 12,  'tier_c_bonus' => 45,
                'sort_order'     => 2,
            ],
            [
                'role'           => 'marketer',
                'slug'           => 'new_leads',
                'name_ar'        => 'العملاء المحتملون الجدد',
                'name_en'        => 'New Leads (Inbound Messages)',
                'description_ar' => 'عدد رسائل الاستفسار الواردة عبر منصات التواصل',
                'description_en' => 'Number of inbound enquiry messages via social platforms',
                'unit'           => 'messages',
                'direction'      => 'higher_is_better',
                'max_bonus_pct'  => 40,
                'tier_a_min'     => 10,  'tier_a_bonus' => 10,
                'tier_b_min'     => 25,  'tier_b_bonus' => 25,
                'tier_c_min'     => 40,  'tier_c_bonus' => 40,
                'sort_order'     => 3,
            ],
            [
                'role'           => 'marketer',
                'slug'           => 'content_creation',
                'name_ar'        => 'إنتاج المحتوى',
                'name_en'        => 'Content Creation',
                'description_ar' => 'عدد القطع المنشورة شهرياً (منشورات، ريلز، ستوريز...)',
                'description_en' => 'Monthly published pieces (posts, reels, stories...)',
                'unit'           => 'pieces',
                'direction'      => 'higher_is_better',
                'max_bonus_pct'  => 45,
                'tier_a_min'     => 8,   'tier_a_bonus' => 15,
                'tier_b_min'     => 12,  'tier_b_bonus' => 30,
                'tier_c_min'     => 16,  'tier_c_bonus' => 45,
                'sort_order'     => 4,
            ],

            // ── Customer Support ──────────────────────────────────────────
            [
                'role'           => 'customer_support',
                'slug'           => 'ticket_resolution_rate',
                'name_ar'        => 'معدل حل التذاكر',
                'name_en'        => 'Ticket Resolution Rate',
                'description_ar' => '% التذاكر المغلقة بنجاح خلال الشهر',
                'description_en' => '% of tickets successfully closed within the month',
                'unit'           => '%',
                'direction'      => 'higher_is_better',
                'max_bonus_pct'  => 45,
                'tier_a_min'     => 70,  'tier_a_bonus' => 15,
                'tier_b_min'     => 85,  'tier_b_bonus' => 30,
                'tier_c_min'     => 95,  'tier_c_bonus' => 45,
                'sort_order'     => 1,
            ],
            [
                'role'           => 'customer_support',
                'slug'           => 'response_time',
                'name_ar'        => 'وقت الاستجابة',
                'name_en'        => 'Average Response Time',
                'description_ar' => 'متوسط وقت الاستجابة بالساعات (أقل = أفضل)',
                'description_en' => 'Average response time in hours (lower is better)',
                'unit'           => 'hours',
                'direction'      => 'lower_is_better',
                'max_bonus_pct'  => 40,
                // For lower_is_better: tier_c_min is the best (lowest) threshold
                'tier_a_min'     => 6,   'tier_a_bonus' => 10,
                'tier_b_min'     => 4,   'tier_b_bonus' => 25,
                'tier_c_min'     => 1,   'tier_c_bonus' => 40,
                'sort_order'     => 2,
            ],
            [
                'role'           => 'customer_support',
                'slug'           => 'escalations',
                'name_ar'        => 'التصعيدات',
                'name_en'        => 'Escalations',
                'description_ar' => 'عدد الحالات التي صعّدها الموظف بسبب خطأ أو تقصير (أقل = أفضل)',
                'description_en' => 'Number of cases escalated due to staff error (lower is better)',
                'unit'           => 'cases',
                'direction'      => 'lower_is_better',
                'max_bonus_pct'  => 40,
                'tier_a_min'     => 4,   'tier_a_bonus' => 10,
                'tier_b_min'     => 2,   'tier_b_bonus' => 25,
                'tier_c_min'     => 1,   'tier_c_bonus' => 40,
                'sort_order'     => 3,
            ],
            [
                'role'           => 'customer_support',
                'slug'           => 'csat',
                'name_ar'        => 'رضا العملاء',
                'name_en'        => 'Customer Satisfaction (CSAT)',
                'description_ar' => 'متوسط تقييم العميل عبر الاستطالع بعد كل تذكرة (من 5)',
                'description_en' => 'Average customer rating via post-ticket survey (out of 5)',
                'unit'           => '/ 5',
                'direction'      => 'higher_is_better',
                'max_bonus_pct'  => 45,
                'tier_a_min'     => 3.0,  'tier_a_bonus' => 15,
                'tier_b_min'     => 4.0,  'tier_b_bonus' => 30,
                'tier_c_min'     => 4.5,  'tier_c_bonus' => 45,
                'sort_order'     => 4,
            ],

            // ── Analyst ───────────────────────────────────────────────────
            [
                'role'           => 'analyst',
                'slug'           => 'live_sessions',
                'name_ar'        => 'الجلسات المباشرة',
                'name_en'        => 'Live Sessions',
                'description_ar' => 'عدد بث اثات تيليغرام المباشرة للتداول شهرياً',
                'description_en' => 'Number of live Telegram trading broadcasts per month',
                'unit'           => 'broadcasts',
                'direction'      => 'higher_is_better',
                'max_bonus_pct'  => 40,
                'tier_a_min'     => 2,   'tier_a_bonus' => 10,
                'tier_b_min'     => 4,   'tier_b_bonus' => 25,
                'tier_c_min'     => 6,   'tier_c_bonus' => 40,
                'sort_order'     => 1,
            ],
            [
                'role'           => 'analyst',
                'slug'           => 'win_rate',
                'name_ar'        => 'معدل الربح (PIPS)',
                'name_en'        => 'Win Rate (PIPS)',
                'description_ar' => 'نسبة الإشارات التي حققت الهدف (PIPS)',
                'description_en' => 'Percentage of signals that hit the target (PIPS)',
                'unit'           => '%',
                'direction'      => 'higher_is_better',
                'max_bonus_pct'  => 50,
                'tier_a_min'     => 50,  'tier_a_bonus' => 15,
                'tier_b_min'     => 65,  'tier_b_bonus' => 30,
                'tier_c_min'     => 80,  'tier_c_bonus' => 50,
                'sort_order'     => 2,
            ],
            [
                'role'           => 'analyst',
                'slug'           => 'Pips Count',
                'name_ar'        => 'عدد النقاط',
                'name_en'        => 'Pips Count',
                'description_ar' => 'إجمالي النقاط التداول المرسلة عبر القنوات شهرياً',
                'description_en' => 'Total trading pips sent via channels per month',
                'unit'           => 'pips',
                'direction'      => 'higher_is_better',
                'max_bonus_pct'  => 40,
                'tier_a_min'     => 2000,  'tier_a_bonus' => 15,
                'tier_b_min'     => 6000,  'tier_b_bonus' => 30,
                'tier_c_min'     => 10000,  'tier_c_bonus' => 40,
                'sort_order'     => 3,
            ],
            [
                'role'           => 'analyst',
                'slug'           => 'reels_production',
                'name_ar'        => 'تصوير الريلز',
                'name_en'        => 'Reels Production',
                'description_ar' => 'عدد ريلز محتوى التداول المنتجة شهرياً',
                'description_en' => 'Number of trading-content reels produced per month',
                'unit'           => 'reels',
                'direction'      => 'higher_is_better',
                'max_bonus_pct'  => 30,
                'tier_a_min'     => 2,   'tier_a_bonus' => 10,
                'tier_b_min'     => 4,   'tier_b_bonus' => 25,
                'tier_c_min'     => 6,   'tier_c_bonus' => 30,
                'sort_order'     => 4,
            ],
            [
                'role'           => 'analyst',
                'slug'           => 'trader_followup',
                'name_ar'        => 'متابعة المتداولين',
                'name_en'        => 'Trader Follow-up',
                'description_ar' => 'نسبة الاستفسارات التي أجيب عليها خلال 24 ساعة',
                'description_en' => '% of trader enquiries answered within 24 hours',
                'unit'           => '%',
                'direction'      => 'higher_is_better',
                'max_bonus_pct'  => 40,
                'tier_a_min'     => 60,  'tier_a_bonus' => 15,
                'tier_b_min'     => 70,  'tier_b_bonus' => 30,
                'tier_c_min'     => 80,  'tier_c_bonus' => 40,
                'sort_order'     => 5,
            ],
        ];

        foreach ($kpis as $kpi) {
            KpiDefinition::updateOrCreate(
                ['role' => $kpi['role'], 'slug' => $kpi['slug']],
                $kpi
            );
        }
    }
}
